databases: []

services:
  - type: web
    runtime: node
    name: techvault-api
    repo: https://github.com/Jabirmahmud0/techvault
    plan: free
    buildCommand: npm ci --include=dev && npx turbo run build --filter=api
    startCommand: node apps/api/dist/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
